services:
  - type: web
    name: scratch-comment-bot-python
    runtime: python
    rootDir: scratch-comment-bot-python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --threads 4 --timeout 120
    healthCheckPath: /
    autoDeployTrigger: commit
